# Generated by Django 5.2.14 on 2026-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True)),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
