# Generated by Django 5.2.15 on 2026-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
    ]
