# Generated by Django 5.2.15 on 2026-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options_alter_place_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления'),
        ),
    ]
