# Generated by Django 5.2.14 on 2026-05-29 12:43

from django.db import migrations


def fill_prices(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    for item in OrderItem.objects.select_related("product").only("product__price"):
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0041_alter_orderitem_price"),
    ]

    operations = [
        migrations.RunPython(fill_prices, reverse_code=migrations.RunPython.noop)
    ]
