# Generated by Django 5.2.14 on 2026-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_fill_orderitem_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('canceled', 'Отменён'), ('preparing', 'В сборке'), ('delivering', 'В доставке'), ('delivered', 'Доставлен')], default='new', max_length=50, verbose_name='статус заказа'),
        ),
    ]
