# Generated by Django 5.2.14 on 2026-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий к заказу'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='foodcartapp_status_99d57e_idx'),
        ),
    ]
