# Generated by Django 5.2.14 on 2026-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_status_99d57e_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cooking', 'Готовится'), ('canceled', 'Отменён'), ('preparing', 'В сборке'), ('delivering', 'В доставке'), ('delivered', 'Доставлен')], default='new', max_length=50, verbose_name='статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('card', 'Карта'), ('money', 'Наличные')], default='money', max_length=50, verbose_name='способ оплаты'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='foodcartapp_order_s_91868e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='foodcartapp_payment_9a53be_idx'),
        ),
    ]
