# Generated by Django 5.2.15 on 2026-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('card', 'Карта'), ('money', 'Наличные')], max_length=50, verbose_name='способ оплаты'),
        ),
    ]
